# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SOCADEFKFilterCpp <- function(I, V, Temp, Time, theta_0, ocv_0, SOC_0, P, Q, R, K, dual, trace, trace_limit) {
    .Call('_BatteryPrognostics_SOCADEFKFilterCpp', PACKAGE = 'BatteryPrognostics', I, V, Temp, Time, theta_0, ocv_0, SOC_0, P, Q, R, K, dual, trace, trace_limit)
}

ADUKF_Cpp <- function(I, V, Temp, Time, OCV_0, Theta_0, sigma_0, R_X, R_V, SOC_0, K, trace, trace_limit) {
    .Call('_BatteryPrognostics_ADUKF_Cpp', PACKAGE = 'BatteryPrognostics', I, V, Temp, Time, OCV_0, Theta_0, sigma_0, R_X, R_V, SOC_0, K, trace, trace_limit)
}

SOCDEFKFilterCpp <- function(I, V, theta_0, ocv_0, SOC_0, C_max, P, Q, R, dt, K, trace, trace_limit) {
    .Call('_BatteryPrognostics_SOCDEFKFilterCpp', PACKAGE = 'BatteryPrognostics', I, V, theta_0, ocv_0, SOC_0, C_max, P, Q, R, dt, K, trace, trace_limit)
}

RCKCpp <- function(I, IC, IF, R0, Rk, Ck, Cap, OCV, SOCList, IList, dt, SOCStart, trace, trace_limit) {
    .Call('_BatteryPrognostics_RCKCpp', PACKAGE = 'BatteryPrognostics', I, IC, IF, R0, Rk, Ck, Cap, OCV, SOCList, IList, dt, SOCStart, trace, trace_limit)
}

#' @title Corrects time
#' @description Correction of time in the case of inconsistant time-step sizes.
#' 
#' @param I A vector containing the current.
#' @param V A vector containing the voltage.
#' @param T A vector containing the time.
#' 
#' @return A matrix containing the corrected time, and interpolated current and voltage.
#' @export
correct_time <- function(I, V, T) {
    .Call('_BatteryPrognostics_correct_time', PACKAGE = 'BatteryPrognostics', I, V, T)
}

compare_windows_raw_cpp <- function(I1, I2, V1, V2, W, R, epsilon, delta, trace, trace_limit) {
    .Call('_BatteryPrognostics_compare_windows_raw_cpp', PACKAGE = 'BatteryPrognostics', I1, I2, V1, V2, W, R, epsilon, delta, trace, trace_limit)
}

compare_windows_single_cpp <- function(I1, I2, V1, V2, RI2, W2, W, R, epsilon, delta, trace, trace_limit) {
    .Call('_BatteryPrognostics_compare_windows_single_cpp', PACKAGE = 'BatteryPrognostics', I1, I2, V1, V2, RI2, W2, W, R, epsilon, delta, trace, trace_limit)
}

compare_windows_ga_cpp <- function(I1, I2, V1, V2, Temp1, Temp2, mutation_window, restrict_temperature, restrict_voltage, Wmin, Wmax, Imin, N_evolution, N_keep, trace, trace_limit, seed) {
    .Call('_BatteryPrognostics_compare_windows_ga_cpp', PACKAGE = 'BatteryPrognostics', I1, I2, V1, V2, Temp1, Temp2, mutation_window, restrict_temperature, restrict_voltage, Wmin, Wmax, Imin, N_evolution, N_keep, trace, trace_limit, seed)
}

compare_windows_variable_cpp <- function(I1, I2, V1, V2, Wmin, Wmax, epsilon, delta, trace, trace_limit) {
    .Call('_BatteryPrognostics_compare_windows_variable_cpp', PACKAGE = 'BatteryPrognostics', I1, I2, V1, V2, Wmin, Wmax, epsilon, delta, trace, trace_limit)
}

extract_resistance_cpp <- function(I, V, T_s, epsilon, Q_max, eta, SOC_0) {
    .Call('_BatteryPrognostics_extract_resistance_cpp', PACKAGE = 'BatteryPrognostics', I, V, T_s, epsilon, Q_max, eta, SOC_0)
}

particle_filtering_cpp <- function(V, I, Temp, Time, OCV_c_pars, OCV_d_pars, RT_pars, Q_pars, L, sigma, SOC_0, K, N, trace, trace_limit) {
    .Call('_BatteryPrognostics_particle_filtering_cpp', PACKAGE = 'BatteryPrognostics', V, I, Temp, Time, OCV_c_pars, OCV_d_pars, RT_pars, Q_pars, L, sigma, SOC_0, K, N, trace, trace_limit)
}

