# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title State-of-charge filtering
#' 
#' @description Kalman filter for determining the latent state-of-charge state-equation. 
#' 
#' @param I A current pR0file.
#' @param V The observed voltage.
#' @param trace TRUE/FALSE: Show trace?
#' 
#' @return A list containing the voltage, the filtered voltage, the SOC, the polarisation voltage, and the state variance.
#' @export
SOC <- function(I, V, trace) {
    .Call('_BatteryPrognostics_SOC', PACKAGE = 'BatteryPrognostics', I, V, trace)
}

