# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SODEFKFilterCpp <- function(I, V, theta_0, ocv_0, SOC_0, C_max, P, Q, R, dt, K, trace, traceLimit) {
    .Call('_BatteryPrognostics_SODEFKFilterCpp', PACKAGE = 'BatteryPrognostics', I, V, theta_0, ocv_0, SOC_0, C_max, P, Q, R, dt, K, trace, traceLimit)
}

SODEFKSmoothCpp <- function(I, V, theta_0, ocv_0, SOC_0, C_max, P, Q, R, dt, K, trace, traceLimit) {
    .Call('_BatteryPrognostics_SODEFKSmoothCpp', PACKAGE = 'BatteryPrognostics', I, V, theta_0, ocv_0, SOC_0, C_max, P, Q, R, dt, K, trace, traceLimit)
}

SODEFKTESTCpp <- function(I, V, theta_0, ocv_parameters, SOC_0, C_max, P, Q, R, dt, K, trace, traceLimit) {
    .Call('_BatteryPrognostics_SODEFKTESTCpp', PACKAGE = 'BatteryPrognostics', I, V, theta_0, ocv_parameters, SOC_0, C_max, P, Q, R, dt, K, trace, traceLimit)
}

RCKCpp <- function(I, IC, IF, R0, Rk, Ck, Cap, OCV, SOCList, IList, dt, SOCStart, trace, traceLimit) {
    .Call('_BatteryPrognostics_RCKCpp', PACKAGE = 'BatteryPrognostics', I, IC, IF, R0, Rk, Ck, Cap, OCV, SOCList, IList, dt, SOCStart, trace, traceLimit)
}

ParameterUKFCpp <- function(I, V, theta_0, P_0, SOC_0, C_max, eta, dt, K, trace, traceLimit) {
    .Call('_BatteryPrognostics_ParameterUKFCpp', PACKAGE = 'BatteryPrognostics', I, V, theta_0, P_0, SOC_0, C_max, eta, dt, K, trace, traceLimit)
}

